name: Deploy and build app to server

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: "-rltgoDzvO --delete"
                  SOURCE: "/"
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_TARGET }}
            - name: build app in server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: 22
                  script: |
                      cd ${{ secrets.REMOTE_TARGET }}
                      echo -e "${{ secrets.ENV }}" >> .env
                      docker-compose up -d --build
